In [1]:
import numpy as np

In [2]:
mat=np.arange(1,17).reshape(4,-1)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
mat[1:3,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [4]:
mat[0,3]

4

In [5]:
mat[2,2]

11

In [6]:
mat[2]

array([ 9, 10, 11, 12])

In [7]:
mat[:,1]

array([ 2,  6, 10, 14])

In [8]:
mat[:2,:2]

array([[1, 2],
       [5, 6]])

In [9]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
np.where(mat%2==0,mat,0) #if else 
# kalau value dari mat bisa dibagi 2, maka keluarkan angkanya, kalau tidak, ganti isinya dengan 0

array([[ 0,  2,  0,  4],
       [ 0,  6,  0,  8],
       [ 0, 10,  0, 12],
       [ 0, 14,  0, 16]])

# Pandas for Data Analysis

In [11]:
import pandas as pd

## Creating Series
data koleksi 1 dimensi (mirip array 1d pada numpy) pada pandas. Bisa diberi lebal/nama pada index dan menampung jenis data apapun (bukan hanya angka seperti pada array)

In [12]:
mylist=[10,20,30]
labels=['a','b','c']

In [13]:
# Series from list
pd.Series(mylist) #secara default, index pada series berupa angka dimulai dari 0
# perhatikan cara penulisan function Series

0    10
1    20
2    30
dtype: int64

In [14]:
pd.Series(mylist,labels) # memberi nama/label untuk index

a    10
b    20
c    30
dtype: int64

In [15]:
pd.Series(data=mylist, index=labels)

a    10
b    20
c    30
dtype: int64

In [16]:
# Series from array
arr= np.array([10,20,30])
arr

array([10, 20, 30])

In [17]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [18]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [19]:
# Series from Dictionary
myDict={'a':10,'b':20,'c':30}
myDict

{'a': 10, 'b': 20, 'c': 30}

In [20]:
pd.Series(myDict) #key dictionary akan menjadi label Series, value pada dictionary akan menjadi value pada Series

a    10
b    20
c    30
dtype: int64

## Creating Data Frame
DataFrame adalah data 2 dimensi yang merupakan gabungan dari beberapa Series dengan index yang sama.  
DataFrame memiliki kolom dan baris, di mana, 1 kolom berisi satu jenis variabel dengan 1 jenis data tipe, sementara tiap kolom berisi 1 observasi.  

In [21]:
# from lists
kota=['Jakarta','Surabaya','Bandung']
toko=[4,2,2]
penjualan=[10000,6000,8000]

In [22]:
pd.DataFrame(data=[kota,toko,penjualan]) # perhatikan cara penulisan DataFrame
#secara default, setiap list jadi 1 baris, padahal, dalam kasus ini kita ingin 1 list menjadi 1 kolom

0         1        2
0  Jakarta  Surabaya  Bandung
1        4         2        2
2    10000      6000     8000

In [23]:
pd.DataFrame(data=[kota,toko,penjualan])[0] #perhatikan data type
# tiap kolom memiliki data tipe seragam, jadi, jika kita memiliki data tipe integer dan string pada 1 kolom
# maka data tipe di kolom tersebut akan menjadi object/string

0    Jakarta
1          4
2      10000
Name: 0, dtype: object

In [24]:
pd.DataFrame(zip(kota,toko,penjualan))
#zip digunakan untuk membuat tuple berisikan data di posisi tertentu secara berurutan dari beberapa iterable

0  1      2
0   Jakarta  4  10000
1  Surabaya  2   6000
2   Bandung  2   8000

In [25]:
pd.DataFrame(zip(kota,toko,penjualan),columns=['kota', 'toko', 'penjualan'],index='a b c'.split())

kota  toko  penjualan
a   Jakarta     4      10000
b  Surabaya     2       6000
c   Bandung     2       8000

In [26]:
pd.DataFrame(data=[kota,toko,penjualan]).T # bisa begini, tapi hati-hati dengan karena tipe data bisa tidak sesuai

0  1      2
0   Jakarta  4  10000
1  Surabaya  2   6000
2   Bandung  2   8000

In [27]:
# from list in list
mylist=[[1,2,3,4],
       [5,6,7,8],
       [9,10,11,12]]
mylist # semua list di dalam list harus berukuran sama

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [28]:
pd.DataFrame(mylist) #tiap list di dalam list akan menjadi 1 baris

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [29]:
pd.DataFrame(mylist,index='a b c'.split(),columns='w x y z'.split())

w   x   y   z
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [30]:
# DataFrame from matrix array
mat=np.arange(1,25).reshape(4,-1)
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [31]:
pd.DataFrame(mat, columns='a b c d e f'.split(), index=['w','x','y','z'])

a   b   c   d   e   f
w   1   2   3   4   5   6
x   7   8   9  10  11  12
y  13  14  15  16  17  18
z  19  20  21  22  23  24

In [32]:
# DataFrame from Dictionary

myDict={
    'Kota':['Jakarta','Surabaya','Bandung'],
    'Toko':[4,2,2],
    'Penjualan':[10000,6000,8000]
}
myDict #panjang value di setiap key harus sama

{'Kota': ['Jakarta', 'Surabaya', 'Bandung'],
 'Toko': [4, 2, 2],
 'Penjualan': [10000, 6000, 8000]}

In [33]:
pd.DataFrame(myDict,index= 'a b c'.split()) #pada DataFrame, setiap key di dictionary akan menjadi nama kolom, 
# value di setiap key menjadi 1 kolom

Kota  Toko  Penjualan
a   Jakarta     4      10000
b  Surabaya     2       6000
c   Bandung     2       8000

**Latihan** Buatlah DataFrame berikut, simpan di variabel df

In [34]:
df=pd.DataFrame({'name': ['Raven Bierman', 'Valter Havers', 'Marko Mendell', 'Takahiro Momota','Yahiko Tilemans', 'Dina Rebaine'],
    'gender': ['Female','Male','Male','Male','Male','Female'],
    'hire date': ['2016-12-04','2018-04-13','2018-07-04','2016-11-18','2017-05-26','2015-03-20'],
    'gross salary':[7000000,7000000,15000000,12000000,20000000,15000000]},
    index=[100111,100112,200210,200211,200312,300207])

In [35]:
df

name  gender   hire date  gross salary
100111    Raven Bierman  Female  2016-12-04       7000000
100112    Valter Havers    Male  2018-04-13       7000000
200210    Marko Mendell    Male  2018-07-04      15000000
200211  Takahiro Momota    Male  2016-11-18      12000000
200312  Yahiko Tilemans    Male  2017-05-26      20000000
300207     Dina Rebaine  Female  2015-03-20      15000000

## Index and Selection

In [36]:
# tanpa function apapun
df['name'] # index kolom, baru baris
# memanggil kolom name dari dataframe df

100111      Raven Bierman
100112      Valter Havers
200210      Marko Mendell
200211    Takahiro Momota
200312    Yahiko Tilemans
300207       Dina Rebaine
Name: name, dtype: object

In [37]:
df['name'][100111] # menampilkan nama karyawan dengan nomor index 100111

'Raven Bierman'

In [38]:
df['name'][[100111,200211]] #fancy indexing, memanggil nama karyawan dengan 2 nomor index tidak berurutan

100111      Raven Bierman
200211    Takahiro Momota
Name: name, dtype: object

In [39]:

contoh=pd.DataFrame(mylist)
contoh

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [40]:
contoh[0][:2] #slicing, bisa dipakai dengan index default

0    1
1    5
Name: 0, dtype: int64

In [41]:
df[['name','gross salary']] #perhatikan jumlah bracket
# memanggil lebih dari 1 kolom

name  gross salary
100111    Raven Bierman       7000000
100112    Valter Havers       7000000
200210    Marko Mendell      15000000
200211  Takahiro Momota      12000000
200312  Yahiko Tilemans      20000000
300207     Dina Rebaine      15000000

In [42]:
# attribute access untuk memanggil kolom
# tidak disarankan dipakai
df.name

100111      Raven Bierman
100112      Valter Havers
200210      Marko Mendell
200211    Takahiro Momota
200312    Yahiko Tilemans
300207       Dina Rebaine
Name: name, dtype: object

In [43]:
contoh['min']=[22,23,24]
contoh

0   1   2   3  min
0  1   2   3   4   22
1  5   6   7   8   23
2  9  10  11  12   24

In [44]:
contoh.min # output aneh, karena min juga merupakan nama fuction untuk dataframe

<bound method DataFrame.min of    0   1   2   3  min
0  1   2   3   4   22
1  5   6   7   8   23
2  9  10  11  12   24>

In [45]:
contoh['min'] #lebih disarankan

0    22
1    23
2    24
Name: min, dtype: int64

In [46]:
# dengan function loc
df

name  gender   hire date  gross salary
100111    Raven Bierman  Female  2016-12-04       7000000
100112    Valter Havers    Male  2018-04-13       7000000
200210    Marko Mendell    Male  2018-07-04      15000000
200211  Takahiro Momota    Male  2016-11-18      12000000
200312  Yahiko Tilemans    Male  2017-05-26      20000000
300207     Dina Rebaine  Female  2015-03-20      15000000

In [47]:
df.loc[200211] # untuk memanggil data berdasarkan label index/baris #perhatikan bahwa loc memakai []

name            Takahiro Momota
gender                     Male
hire date            2016-11-18
gross salary           12000000
Name: 200211, dtype: object

In [48]:
df.loc[100112:200312] #slicing berdasarkan LABEL index
#perhatikan bahwa tidak seperti slicing biasa, data 200312 juga ikut terpanggil

name gender   hire date  gross salary
100112    Valter Havers   Male  2018-04-13       7000000
200210    Marko Mendell   Male  2018-07-04      15000000
200211  Takahiro Momota   Male  2016-11-18      12000000
200312  Yahiko Tilemans   Male  2017-05-26      20000000

In [49]:
df.loc[200211,'hire date'] #hire date dari karyawan dengan nomor index 200211

'2016-11-18'

In [50]:
# dengan fungsi iloc
df

name  gender   hire date  gross salary
100111    Raven Bierman  Female  2016-12-04       7000000
100112    Valter Havers    Male  2018-04-13       7000000
200210    Marko Mendell    Male  2018-07-04      15000000
200211  Takahiro Momota    Male  2016-11-18      12000000
200312  Yahiko Tilemans    Male  2017-05-26      20000000
300207     Dina Rebaine  Female  2015-03-20      15000000

In [51]:
df.iloc[2] #memanggil data berdasarkan **posisi** index/kolom

name            Marko Mendell
gender                   Male
hire date          2018-07-04
gross salary         15000000
Name: 200210, dtype: object

In [52]:
df.iloc[:,1] # memanggil semua data pada kolom posisi 1 (gender)

100111    Female
100112      Male
200210      Male
200211      Male
200312      Male
300207    Female
Name: gender, dtype: object

In [53]:
df

name  gender   hire date  gross salary
100111    Raven Bierman  Female  2016-12-04       7000000
100112    Valter Havers    Male  2018-04-13       7000000
200210    Marko Mendell    Male  2018-07-04      15000000
200211  Takahiro Momota    Male  2016-11-18      12000000
200312  Yahiko Tilemans    Male  2017-05-26      20000000
300207     Dina Rebaine  Female  2015-03-20      15000000

In [54]:
df[1:4] # memanggil data pada posisi index 1 sampai sebelum 4

name gender   hire date  gross salary
100112    Valter Havers   Male  2018-04-13       7000000
200210    Marko Mendell   Male  2018-07-04      15000000
200211  Takahiro Momota   Male  2016-11-18      12000000

In [55]:
df.iloc[::2] #memanggil semua data, dilongkap 1 (karena step=2)

name  gender   hire date  gross salary
100111    Raven Bierman  Female  2016-12-04       7000000
200210    Marko Mendell    Male  2018-07-04      15000000
200312  Yahiko Tilemans    Male  2017-05-26      20000000

## Conditional Selection

In [56]:
contoh2=pd.DataFrame(np.arange(0,20).reshape(4,-1))
contoh2

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [57]:
contoh2>10 # conditional statement
# cek apakah tiap data di dataframe contoh2 memiliki nilai lebih bedar dari 10
# output berupa data frame berisi boolean

0      1      2      3      4
0  False  False  False  False  False
1  False  False  False  False  False
2  False   True   True   True   True
3   True   True   True   True   True

In [58]:
contoh2[contoh2>10] # masukkan conditional statement sebagai index, maka output berupa data yang memenuhi syarat tersebut

0     1     2     3     4
0   NaN   NaN   NaN   NaN   NaN
1   NaN   NaN   NaN   NaN   NaN
2   NaN  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [59]:
df

name  gender   hire date  gross salary
100111    Raven Bierman  Female  2016-12-04       7000000
100112    Valter Havers    Male  2018-04-13       7000000
200210    Marko Mendell    Male  2018-07-04      15000000
200211  Takahiro Momota    Male  2016-11-18      12000000
200312  Yahiko Tilemans    Male  2017-05-26      20000000
300207     Dina Rebaine  Female  2015-03-20      15000000

In [60]:
# memanggil data karyawan dengan gender female
df[df['gender']=='Female']
# df.loc[df['gender']=='Female']

name  gender   hire date  gross salary
100111  Raven Bierman  Female  2016-12-04       7000000
300207   Dina Rebaine  Female  2015-03-20      15000000

In [61]:
# menampilkan *nama* karyawan dengan gender Female
df[df['gender']=='Female']['name']
# df.loc[df['gender']=='Female','name']

100111    Raven Bierman
300207     Dina Rebaine
Name: name, dtype: object

In [62]:
# menampilkan *nama dan gaji* karyawan dengan gender Female
df[df['gender']=='Female'][['name','gross salary']]
# df.loc[df['gender']=='Female',['name','gross salary']]

name  gross salary
100111  Raven Bierman       7000000
300207   Dina Rebaine      15000000

In [63]:
df[(df['gender']=='Female') & (df['gross salary']>10000000)]['name']
# menampilkan nama karyawan yang gendernya female DAN gajinya di atas 10juta
# kalau mneggunakan lebih dari 1 kondisi, setiap conditional statement perlu dimasukkan ke dalam (), 
# dipisahkan dengan operator & (and) atau | (or)

300207    Dina Rebaine
Name: name, dtype: object

In [ ]:
## latihan

In [64]:
df

name  gender   hire date  gross salary
100111    Raven Bierman  Female  2016-12-04       7000000
100112    Valter Havers    Male  2018-04-13       7000000
200210    Marko Mendell    Male  2018-07-04      15000000
200211  Takahiro Momota    Male  2016-11-18      12000000
200312  Yahiko Tilemans    Male  2017-05-26      20000000
300207     Dina Rebaine  Female  2015-03-20      15000000

In [65]:
# tampilkan kolom name dan hire date
df[['name','hire date']]
# df.iloc[:,[0,2]]

name   hire date
100111    Raven Bierman  2016-12-04
100112    Valter Havers  2018-04-13
200210    Marko Mendell  2018-07-04
200211  Takahiro Momota  2016-11-18
200312  Yahiko Tilemans  2017-05-26
300207     Dina Rebaine  2015-03-20

In [66]:
# tampilkan nama karyawan dengan index nomor 200312
df.loc[200312,'name']
# df['name'][200312]

'Yahiko Tilemans'

In [67]:
# tampilkan data karyawan yang bernama Marko Mendell
df[df['name']=='Marko Mendell']

name gender   hire date  gross salary
200210  Marko Mendell   Male  2018-07-04      15000000

In [68]:
# tampilkan nama dan gender dari karyawan dengan gaji di atas 10 juta
df[df['gross salary']>10000000][['name','gender']]

name  gender
200210    Marko Mendell    Male
200211  Takahiro Momota    Male
200312  Yahiko Tilemans    Male
300207     Dina Rebaine  Female

In [69]:
# tampilkan nama karyawan yang gendernya Male
df[df['gender']=='Male']['name']

100112      Valter Havers
200210      Marko Mendell
200211    Takahiro Momota
200312    Yahiko Tilemans
Name: name, dtype: object

In [70]:
df

name  gender   hire date  gross salary
100111    Raven Bierman  Female  2016-12-04       7000000
100112    Valter Havers    Male  2018-04-13       7000000
200210    Marko Mendell    Male  2018-07-04      15000000
200211  Takahiro Momota    Male  2016-11-18      12000000
200312  Yahiko Tilemans    Male  2017-05-26      20000000
300207     Dina Rebaine  Female  2015-03-20      15000000

In [71]:
#tampilkan data pada posisi index 3 dan posisi kolom 2
df.iloc[3,2]

'2016-11-18'

In [72]:
#  tampilkan nama karyawan dengan gaji 7000000
df[df['gross salary']==7000000]['name']

100111    Raven Bierman
100112    Valter Havers
Name: name, dtype: object

In [73]:
# tampilkan nama karyawan dengan gender male dan gaji di bawah 10000000
df[(df['gender']=='Male')&(df['gross salary']<10000000)]['name']

100112    Valter Havers
Name: name, dtype: object

In [74]:
df

name  gender   hire date  gross salary
100111    Raven Bierman  Female  2016-12-04       7000000
100112    Valter Havers    Male  2018-04-13       7000000
200210    Marko Mendell    Male  2018-07-04      15000000
200211  Takahiro Momota    Male  2016-11-18      12000000
200312  Yahiko Tilemans    Male  2017-05-26      20000000
300207     Dina Rebaine  Female  2015-03-20      15000000

In [75]:
df.loc[(df['gender']=='Male')&(df['gross salary']<10000000),'name']

100112    Valter Havers
Name: name, dtype: object