# Modul 2: DATA ANALYSIS

# *Numpy*

Array:
- Tipe data terstruktur yang menyimpan data dengan tipe data yang seragam
- Mutable (itemnya bisa diganti)
- Index dimulai dari 0
- Bisa berbentuk 1D, 2D, 3D, ..., ND

In [105]:
# import library numpy
import numpy as np

## Create Array

In [106]:
# membuat array dari list
list_angka = [[1,2,3], [10,20,30], [100,200,300]]
list_angka

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]

In [107]:
# membuat array berisi angka yg berurut
np.arange(0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.arange(start=0, stop=10, step=2) 

array([0, 2, 4, 6, 8])

In [109]:
# membuat array berisi angka 0 semua
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [110]:
np.zeros((3,5)) # ini matrix 3x3 berisi angka 0 semua

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [111]:
# membuat array berisi angka 1 semua
np.ones(5)

array([1., 1., 1., 1., 1.])

In [112]:
np.ones((4,2)) # ini matrix 4x2 berisi angka 1 semua

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [113]:
# membuat array berisi angka 0 semua dan angka 1 secara diagonal
# identity matrix

np.eye(5) # akan membentuk matrix 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:
# membuat array yang membagi sekian elemen dengan interval yang sama

np.linspace(start=0, stop=100, num=5)
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [115]:
np.linspace(0, 50, 11)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

**Latihan: Buat array dengan output [10, 30, 50, 70]**

In [116]:
np.linspace(10, 70, 4)

array([10., 30., 50., 70.])

In [117]:
np.arange(10,71,20)

array([10, 30, 50, 70])

**Latihan: Buat array dengan output angka 0 semua berbentuk matix 3x4**

In [118]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Buat array dari angka random**

- np.random.rand()
- np.random.randn()
- np.random.randint()

In [119]:
# membuat array berisi angka random anrata 0-1
np.random.rand(5)

array([0.25531005, 0.17883228, 0.05325365, 0.07902435, 0.45599718])

In [120]:
np.random.rand(2,4) # ini martix 2x4 dengan value angka random antara 0-1

array([[0.92405648, 0.4407926 , 0.77392503, 0.3016082 ],
       [0.96261028, 0.87946864, 0.32793112, 0.13784873]])

In [121]:
# membuat array berisi angka random yang terdistribusi normal (rata-ratanya mendekati 0 dan std mendekati 1)

np.random.randn(10)

array([-1.70309104, -0.80307481, -0.06959736,  0.05980232,  0.39957711,
        0.07158728, -0.61008448,  1.58771297,  0.69962798,  0.11131041])

In [122]:
np.random.randn(2,5)

array([[-0.16328017,  0.00504211,  0.57134584, -1.16512541,  1.23173763],
       [-0.91120953, -0.58494805,  1.31553458,  1.04560701, -0.37454808]])

In [123]:
# membuat array berisi angka random integer

np.random.randint(low=10, high=100, size=5) # membuat 5 angka random antara 10-100 bertipe data integer

np.random.randint(10, 100, 5)  

array([74, 61, 43, 39, 33])

In [124]:
# np.random.seed() agar angka randomnya tidak berubah-ubah
np.random.seed(2022)
np.random.randint(0,20,3)

array([13, 16, 17])

## Attributes and Methods

In [125]:
listA = [98, 69, 17, 33, 65, 18, 12, 17, 71, 35]

arr1 = np.array(listA)
arr1

array([98, 69, 17, 33, 65, 18, 12, 17, 71, 35])

In [126]:
listA

[98, 69, 17, 33, 65, 18, 12, 17, 71, 35]

In [127]:
# mengetahui bentuk dari array
arr1.shape

# berarti ini adalah array 1D (vector)

(10,)

In [128]:
listB = [[98, 69, 17, 33, 65, 18, 12, 17, 71, 35]]

arr2 = np.array(listB)
arr2

array([[98, 69, 17, 33, 65, 18, 12, 17, 71, 35]])

In [129]:
arr2.shape # ini array 2D (matix) 1x10

(1, 10)

In [130]:
listC = [[98, 69, 17], [33, 65, 18], [12, 17, 71]]

arr3 = np.array(listC)
arr3

array([[98, 69, 17],
       [33, 65, 18],
       [12, 17, 71]])

In [131]:
arr3.shape

(3, 3)

In [132]:
# Ubah shape sebuah array dengan np.reshape()
arr1.shape

(10,)

In [133]:
arr1.reshape(10, 1)

array([[98],
       [69],
       [17],
       [33],
       [65],
       [18],
       [12],
       [17],
       [71],
       [35]])

In [134]:
arr1.reshape(1,10)

array([[98, 69, 17, 33, 65, 18, 12, 17, 71, 35]])

In [135]:
arr1

array([98, 69, 17, 33, 65, 18, 12, 17, 71, 35])

In [136]:
# bisa direshape asalkan jumlah itemnya sama
arr1.reshape(2,5)

array([[98, 69, 17, 33, 65],
       [18, 12, 17, 71, 35]])

In [137]:
# kalau shapenya berbeda maka akan error
arr1.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [142]:
arr3

array([[98, 69, 17],
       [33, 65, 18],
       [12, 17, 71]])

In [143]:
# mengubah dari array 2D menjadi array 1D 
arr3.reshape(9,)

array([98, 69, 17, 33, 65, 18, 12, 17, 71])

In [144]:
# mengubah dari array 2D menjadi array 1D tanpa harus mengetahui jumlah itemnya
arr3.reshape(-1)

array([98, 69, 17, 33, 65, 18, 12, 17, 71])

In [145]:
arr3

array([[98, 69, 17],
       [33, 65, 18],
       [12, 17, 71]])

In [146]:
# menampilkan nilai maximum
arr3.max()

98

In [147]:
# menampilkan nilai minimum
arr3.min()

12

In [148]:
# menampilkan posisi dari nilai maximum
arr3.argmax()

0

In [149]:
# menampilkan posisi dari nilai minimum
arr3.argmin()

6

In [150]:
# cek tipe data dari array
arr3.dtype

dtype('int64')

## Indexing

**List**

In [151]:
listA

[98, 69, 17, 33, 65, 18, 12, 17, 71, 35]

In [152]:
listA[2:4]

[17, 33]

In [153]:
listA[:]

[98, 69, 17, 33, 65, 18, 12, 17, 71, 35]

In [154]:
listA[-3:]

[17, 71, 35]

**Array**

Indexing array mirip dengan list

In [155]:
arr1

array([98, 69, 17, 33, 65, 18, 12, 17, 71, 35])

In [156]:
# indexing 1 item
arr1[2]

17

In [157]:
# slicing beberapa item
arr1[2:4]

array([17, 33])

In [158]:
# slicing dengan step 2
arr1[0:11:2]

array([98, 17, 65, 12, 71])

In [159]:
arr1[::2]

array([98, 17, 65, 12, 71])

In [160]:
# slicing dengan step mundur 1 langkah (kurang item index 0)
arr1[-1:0:-1]

array([35, 71, 17, 12, 18, 65, 33, 17, 69])

In [161]:
# slicing dengan step mundur 1 langkah (yg benar)
arr1[::-1]

array([35, 71, 17, 12, 18, 65, 33, 17, 69, 98])

In [162]:
arr1

array([98, 69, 17, 33, 65, 18, 12, 17, 71, 35])

In [163]:
# mengganti value item dari array

arr1[0:3] = [100,200,300]
arr1

array([100, 200, 300,  33,  65,  18,  12,  17,  71,  35])

In [164]:
# mengganti value item dari array

arr1[0:3] = 10
arr1

array([10, 10, 10, 33, 65, 18, 12, 17, 71, 35])

**Catatan: Hati-hati dengan slicing pada array**

In [165]:
arr4 = np.arange(0,11,1)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [166]:
slicing_of_arr4 = arr4[0:5]
slicing_of_arr4

array([0, 1, 2, 3, 4])

In [167]:
slicing_of_arr4[:] = 99
slicing_of_arr4

array([99, 99, 99, 99, 99])

In [168]:
# 5 item pertama pada arr4 ikut berubah jadi 99
arr4

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

**Agar tidak mengubah array awalnya, kita gunakan np.copy()**

In [169]:
arr5 = np.arange(0,11,1)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
slicing_baru = arr5[0:5].copy()
slicing_baru

array([0, 1, 2, 3, 4])

In [171]:
slicing_baru[:] = 88
slicing_baru

array([88, 88, 88, 88, 88])

In [172]:
# arr5 yang awal tetap sebagaimana adanya
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Slicing array 2D (matrix)**

In [173]:
arr_2D = np.array([[10,15,20], [25,30,35], [40,45,50]])
arr_2D

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [174]:
arr_2D[1]

array([25, 30, 35])

In [175]:
arr_2D[1][0:3]

array([25, 30, 35])

In [176]:
arr_2D[1][:]

array([25, 30, 35])

In [177]:
arr_2D[2][2]

50

In [178]:
arr_2D

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [179]:
# Hati hati dengan slicing seperti ini
arr_2D[0:3][0]

array([10, 15, 20])

In [180]:
# array[baris, kolom]
arr_2D[0:3, 0]

array([10, 25, 40])

In [181]:
arr_2D[:, 0]

array([10, 25, 40])

In [182]:
# slicing baris 1 sampai akhir, kolom pertama sampai kolom 1
arr_2D[1: , :2]

array([[25, 30],
       [40, 45]])

**Fancy Indexing**

In [183]:
arr6 = np.arange(0,100,10)
arr6

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [184]:
# cara indexing yang tidak berurutan
arr6[[5,7,1]]

array([50, 70, 10])

In [185]:
arr7 = np.arange(0,9).reshape((3,3))
arr7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [186]:
arr7[[2,0]]

array([[6, 7, 8],
       [0, 1, 2]])

## Conditional Selection

In [187]:
arr8 = np.arange(0,10,1)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
# condition
arr8 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [189]:
# menampilkan item pada arr8 yang kondisinya True
arr8[arr8 > 5]

array([6, 7, 8, 9])

In [190]:
# kondisi disimpan dalam variable
genap = arr8 % 2 == 0
genap

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [191]:
arr8[genap]

array([0, 2, 4, 6, 8])

In [192]:
arr8[arr8 % 2 == 0]

array([0, 2, 4, 6, 8])

## Arithmetic

In [193]:
arr8 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
arr8 + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [195]:
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
arr8 + [0,10,20,30,40,50,60,70,80,90]

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [197]:
arr8 + [0,10,20,30,40]

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [ ]:
arr8*arr8

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr8/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
# array 1D
arr_1D = np.array([1,2,3])
arr_1D

array([1, 2, 3])

In [ ]:
# array 2D
arr_2D = np.array([[10, 15, 20], [25, 30, 35], [40, 45, 50]])
arr_2D

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [ ]:
arr_2D * 10

array([[100, 150, 200],
       [250, 300, 350],
       [400, 450, 500]])

In [ ]:
arr_2D * arr_1D

array([[ 10,  30,  60],
       [ 25,  60, 105],
       [ 40,  90, 150]])

In [ ]:
arr_1D * arr_2D

array([[ 10,  30,  60],
       [ 25,  60, 105],
       [ 40,  90, 150]])

In [ ]:
# dot product
np.dot(arr_2D, arr_1D)

array([100, 190, 280])

In [ ]:
arr_2D

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [216]:
arr_baru = np.array([[1,2,3],[4,5,6]])
arr_baru

array([[1, 2, 3],
       [4, 5, 6]])

In [217]:
np.dot(arr_2D, arr_baru)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
arr_2D * arr_baru

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
arr_coba = np.array([[1,2], [3,4], [5,6]])
arr_coba

array([[1, 2],
       [3, 4],
       [5, 6]])

In [229]:
arr_2D * arr_coba

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [230]:
# untuk dot product, kolom matrix kiri jumlahnya harus sama dengan baris matrix kanan
np.dot(arr_2D, arr_coba)

array([[155, 200],
       [290, 380],
       [425, 560]])

## Function Lain

In [ ]:
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr8)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sin(arr8)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr8)

/var/folders/fr/pqwkzlkd6cjcg8_gpp3j_mj80000gn/T/ipykernel_11489/145059815.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr8)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.exp(arr8)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
# menyelipkan sebuah nilai pada array

# menyelipkan angka 100 di index 5
np.insert(arr8, 5, 100)

array([  0,   1,   2,   3,   4, 100,   5,   6,   7,   8,   9])

In [ ]:
np.delete(arr8, 2)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.append(arr8, 99)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 99])

In [ ]:
arr_2D

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [218]:
arr_baru

array([[1, 2, 3],
       [4, 5, 6]])

In [223]:
arr_coba

array([[1, 2],
       [3, 4],
       [5, 6]])

In [224]:
# menggabungkan pada baris
np.concatenate((arr_2D, arr_baru), axis=0)

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [225]:
np.concatenate((arr_2D, arr_coba), axis=1)

array([[10, 15, 20,  1,  2],
       [25, 30, 35,  3,  4],
       [40, 45, 50,  5,  6]])

In [226]:
arr_coba #matrix 3x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [227]:
#transpose --> kolom menjadi baris
arr_coba.T

array([[1, 3, 5],
       [2, 4, 6]])

In [228]:
#transpose --> kolom menjaid baris
arr_coba.transpose()

array([[1, 3, 5],
       [2, 4, 6]])